name: Deploy production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run build_prod
      - run: cp _redirects build/_redirects
      - uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '3'
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Use branch name to indicate Cloudflare environment: (main | staging)
          # Cloudflare does not deploy by itself so the value is only used to
          # determine the target environment according to defined rules.
          command: pages deploy build --project-name=website --branch=main
